apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: dev-research-app
spec:
  selector:
    app: research-app
    component: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
