apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets
  namespace: dev-research-app
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        iam: {}