apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: dev-research-app
spec:
  selector:
    app: research-app
    component: mongo
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
